version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: shipper
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: ''
      REDIS_DATABASE: '0'
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
