#builder stage

FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN sh -c 'npm install 2>&1 | sed "s/^/[INSTALL] /"'

COPY . .

RUN sh -c 'npm run build 2>&1 | sed "s/^/[BUILD] /"'

#runner stage

FROM node:18-alpine AS runner

WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN sh -c 'npm ci --only=production 2>&1 | sed "s/^/[INSTALL] /"'

CMD [ "node", "dist/index.js" ]