name: Deploy to Production

on:
  push:
    branches:
      - testing
    
jobs:
  seperate_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Make seperate directories for each server
        run: |
          npm run build:deploy

      - name: Deploy Main Server
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.BUILD_SERVER_IP }} >> ~/.ssh/known_hosts

          echo "${{ secrets.BUILD_SERVER_KEY }}" > build_server.pem
          chmod 700 build_server.pem
          if [[ -d build-server.deploy ]];then
            scp -i build_server.pem -r build-server.deploy/* ubuntu@${{ secrets.BUILD_SERVER_IP }}:/home/ubuntu/demo
          else
            echo "build-server.deploy folder not found"
            exit 1
          fi
          ssh -i build_server.pem ubuntu@${{ secrets.BUILD_SERVER_IP }} << 'EOF'
          cd /home/ubuntu/demo
          npm install
          npm run build

          if [[ -d apps/server/build-server/dist ]];then
          echo "start to run server"
            node apps/server/build-server/dist/server.js
          else
            echo "dist folder is not found!!~"
          fi
          EOF

 